name: Manual workflow
on: workflow_dispatch

jobs:
  triggerPipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Priont TOKEN
        run: echo ${{ secrets.TOKENN }}
      - name: Trigger Changes
        uses: peter-evans/repository-dispatch@v2
        with: 
          token: ${{ secrets.TOKENN }}
          repository: UttU28/Pipeline_Site
          event-type: my-event
          client-payload: '{"github": "${{ toJson(github) }}", "action": "triggered"}'
