name: Manual workflow
on:
  workflow_dispatch:
    inputs: 
      triggerName:
        description: 'Workflow2 Name for Triggering'
        required: true
        default: 'triggerAPI'
      
      gitAccount:
        description: 'GitHub Account Owner'
        required: true
        default: 'UttU28'
      
      gitRepoName:
        description: 'GitHub Repository Name'
        required: true
        default: 'Portfolio_CI-CD_Azure'

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      pat_token: ${{ secrets.TOKENN }}
      # payload_Baseline_Number: "BSL_001"
      # payload_Baseline_Revision: "zsfdgsdbgngffdwdx1dxvv2"

    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
         python-version: 3.8 #install the python needed
         
      - name: Install dependencies
        run: |
           cd "$GITHUB_WORKSPACE/deploymentScripts/"
           python -m pip install --upgrade pip
           pip install -r requirements.txt
          
      - name: Trigger the Workflow
        run: |
         cd "$GITHUB_WORKSPACE/deploymentScripts/"
         python $GITHUB_WORKSPACE/deploymentScripts/workflowTrigger.py ${{ env.pat_token }}  ${{ github.event.inputs.gitAccount}}  ${{ github.event.inputs.gitRepoName}} ${{ github.event.inputs.triggerName}}
        #  python $GITHUB_WORKSPACE/deploymentScripts/workflowTrigger.py ${{ env.pat_token }}  ${{ github.event.inputs.gitAccount}}  ${{ github.event.inputs.gitRepoName}} ${{ github.event.inputs.triggerName}} ${{ env.payload_Baseline_Number }} ${{ env.payload_Baseline_Revision }}
    